### ISSUE TITLE
problems with extend functions

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-util#14]
@yotamberk [writes](https://github.com/visjs/vis-timeline/pull/20#issue-301857525):

> All placed using util.extend, util.deepExtend, util.selectiveExtend and util.selectiveDeepExtend would NOT actually do anything!

**Comment by mojoaxel** [comment]
I think we should start by writing tests for these functions...

**Comment by Thomaash** [comment]
What's the problem exactly?

**Comment by Thomaash** [comment]
Util.extend is Object.assign or { ...object }. I don't think we need this at all.

**Comment by mojoaxel** [comment]
I think we need the functions `selectiveExtend` and `selectiveDeepExtend`.
I also think we need a `deepExtend` because destructuring can only overwrite but not extend recursive objects!?

**Comment by Thomaash** [comment]
Yeah, I was talking specifically about `util.extend`, not the others.

**Comment by Thomaash** [comment]
`selectiveExtend` failed in the first test I wrote.

**Comment by Thomaash** [comment]
`selectiveExtend` just ignores the first two objects :smile:. Put there two dummy objects and it will do it's job :smiley:.

**Comment by Thomaash** [comment]
There was probably arguments used initially, I rewrote it to ...rest which wouldn't have the first two args. And it's broken.

**Comment by yotamberk** [comment]
Although these rewrites are great and the tests even better(!), there still seems to be a problem in the timeline option extensions and usage of the util.extend functions.
I'm trying to singular out the problem but not managing yet. 
I must comment that it is REALLY bizarre that even in the `master` branch without any of my PRs, the problem with the extend occurred...

**Comment by Thomaash** [comment]
@yotamberk Could you post here some debugging output. Ideally from something like:
```javascript
console.log('input: ', JSON.stringify({ fields, target: this.options, source: options }))
const output = util.selectiveDeepExtend(fields, this.options, options);
console.log('output: ', JSON.stringify(output))
```

**Comment by mojoaxel** [comment]
@Thomaash Anyway, I think this impotent library could use a 100% test coverage of all functions! :pray:

**Comment by Thomaash** [comment]
We're slowly getting there.

**Comment by yotamberk** [comment]
``` javascript
const optionsOriginal = {"start":null,"end":null,"autoResize":true,"orientation":{"axis":"bottom","item":"bottom"},"width":null,"height":null,"maxHeight":null,"minHeight":null,"rtl":false}
const optionsNew = {"stack":true,"horizontalScroll":true,"zoomKey":"ctrlKey","maxHeight":400,"start":"2019-07-29T19:47:43.037Z","end":"2019-07-30T19:47:43.037Z","editable":true,"margin":{"item":10,"axis":5},"orientation":"top"} 
var fields = [
      'width', 'height', 'minHeight', 'maxHeight', 'autoResize',
      'start', 'end', 'clickToUse', 'dataAttributes', 'hiddenDates',
      'locale', 'locales', 'moment', 'rtl', 'zoomKey', 'horizontalScroll', 'verticalScroll'
    ];
    optionsOriginal = util.selectiveExtend(fields, optionsOriginal , optionsNew ); 
```

**Comment by yotamberk** [comment]
The above example is used in MANY places in the timeline module.
This is not working properly.
The original code was:
`util.selectiveExtend(fields, optionsOriginal , optionsNew );` 
which I changed to: 
`optionsOriginal = util.selectiveExtend(fields, optionsOriginal , optionsNew );`

Not working for any case...

**Comment by Thomaash** [comment]
A test spec that passes and matches my expectation of the behavior of this function:
```typescript
  it('yotamberk', function(): void {
    const target = {
      autoResize: true,
      end: null,
      height: null,
      maxHeight: null,
      minHeight: null,
      orientation: { axis: 'bottom', item: 'bottom' },
      rtl: false,
      start: null,
      width: null,
    }
    const source = {
      editable: true,
      end: '2019-07-30T19:47:43.037Z',
      horizontalScroll: true,
      margin: { item: 10, axis: 5 },
      maxHeight: 400,
      orientation: 'top',
      stack: true,
      start: '2019-07-29T19:47:43.037Z',
      zoomKey: 'ctrlKey',
    }
    const fields = [
      'autoResize',
      'clickToUse',
      'dataAttributes',
      'end',
      'height',
      'hiddenDates',
      'horizontalScroll',
      'locale',
      'locales',
      'maxHeight',
      'minHeight',
      'moment',
      'rtl',
      'start',
      'verticalScroll',
      'width',
      'zoomKey',
    ]

    const copied = selectiveExtend(fields, target, source)

    expect(copied, 'They should be the same instance.').to.equal(target)
    expect(copied, 'The selected properties should be copied by reference').to.deep.equal({
      // new
      end: '2019-07-30T19:47:43.037Z',
      horizontalScroll: true,
      maxHeight: 400,
      start: '2019-07-29T19:47:43.037Z',
      zoomKey: 'ctrlKey',

      // original
      autoResize: true,
      height: null,
      minHeight: null,
      orientation: { axis: 'bottom', item: 'bottom' },
      rtl: false,
      width: null,
    })
  })
```

**Comment by Thomaash** [comment]
What output do you expect?

**Comment by Thomaash** [comment]
BTW: You don't have to reassign, it's the same reference that shouldn't change anything.

**Comment by yotamberk** [comment]
I see that I get back the original target unchanged

**Comment by Thomaash** [comment]
That's weird.

**Comment by Thomaash** [comment]
My fix is not on unpkg.

**Comment by Thomaash** [comment]
But we published a new version right?

**Comment by yotamberk** [comment]
Tell me about it. 
Checkout vis-timeline examples. Nothing is working properly since the options passed to the different components rely on `util.selectiveExtend` which seem to return always the original unchanged options.

**Comment by yotamberk** [comment]
> But we published a new version right?

Yes. even when I use it in the new version, seems not to change

**Comment by Thomaash** [comment]
Try to install this: [vis-util-1.1.3.tgz.zip](https://github.com/visjs/vis-util/files/3444116/vis-util-1.1.3.tgz.zip).

**Comment by yotamberk** [comment]
Checkout master branch. I've pushed the updated version there. If you look at the `file:///C:/Users/yotamberk/Desktop/workspace/vis-timeline/examples/timeline/other/horizontalScroll.html` example in the souremap `Core.js` line 394-404. You can see by yourself that the extend doesn;t seem to work.

**Comment by yotamberk** [comment]
I need to go offline in a short while so I can continue investigating the problem tomorrow.
Thanks for the help!

**Comment by Thomaash** [comment]
No problem.

**Comment by ilancohen** [comment]
I'm having the same issues as @yotamberk.
For instance: https://github.com/visjs/vis-timeline/issues/28

Do we have a fix for this? Or a workaround for now?

**Comment by ilancohen** [comment]
My suspicion is that there is an issue with the importing/bundling of `vis-util` in `vis-timeline`.

**Comment by Thomaash** [comment]
@ilancohen According to package.json on master branch `vis-timeline` depends on defective 1.1.3 version. Upgrade to 1.1.4.

**Comment by ilancohen** [comment]
@Thomaash - yes, but the bundling in `vis-timeline` includes the defective version in the compiled code, so we need to release a new version of `vis-timeline`. I've created a PR there:
visjs/vis-timeline/pull/31

**Comment by Thomaash** [comment]
@ilancohen Does `vis-util` 1.1.4 resolve your issues or is further work on this needed?

**Comment by ilancohen** [comment]
I believe it fixes my problems.

**Comment by Thomaash** [comment]
@ilancohen Thanks for so fast reply.

I'm closing this as it is resolved.
