### ISSUE TITLE
problems with babel destructuring in IE11

### ISSUE THREAD

**Issue by AdrienRedon** [visjs/vis-util#24]
Hello,

vis-util seems to be not compatible with IE11 because there's some destructuring in the builded JS. Is it possible to add https://babeljs.io/docs/en/babel-plugin-transform-destructuring in order to produce a JS compatible with IE11 ?

Thanks in advance :slightly_smiling_face:

**Comment by Thomaash** [comment]
Hi @AdrienRedon,

could you please provide an example of this error? I checked our UMD build and it is ES5 compliant (destructuring is ES2015 feature). All instances I could find are transpiled correctly.

Also are you using the latest (1.1.4 at the time of writing) version?

Thanks.

**Comment by AdrienRedon** [comment]
Hi @Thomaash 
The problem seems to be gone with 1.1.4. (vis-util was a dependency of vis-timeline in my project)
Thanks for the work :wink:
