### ISSUE TITLE
Object expected error on IE11

### ISSUE THREAD

**Issue by molkemon** [visjs/vis-util#37]
Hello, 

timeline is broken in IE11, even the basic examples won't load, error generated in console: 
`Object expected: vis-timeline-graph2d.min.js (25,19969)`

I also tried with the merge timeline-plus branch, same error there. 

Both 4.21 and the latest timeline-plus version do load properly in IE11.

In Firefox, loading works fine for all versions.

**Comment by mojoaxel** [comment]
@Thomaash Can you please configure babel to also support IE11+. Thx!

**Comment by lewdev** [comment]
I had IE11 issues and just added babel-polyfill and it worked.
See: https://babeljs.io/docs/en/usage
or
https://cdnjs.com/libraries/babel-polyfill
