### ISSUE TITLE
Common configuration

### ISSUE THREAD

**Issue by Thomaash** [visjs/vis-util#4]
The packages vis-util and vis-uuid use almost identical configuration. It would probably be a good idea to create a central configuration (ESLint, Prettier, Babel…) so that there is single code style for the whole project or that Babel env doesn't get out of sync.
However I have never done that, ESLint should be quite easy by importing and extending a config in eslintrc, but I have no idea whether other tools support this too.

**Comment by mojoaxel** [comment]
We also could merge vis-uuid into vis-util!? On the other side...vis-uuid is very small. Once it is stable there will be almost no changes needed.

**Comment by Thomaash** [comment]
Well, this now also applies to vis-data which also uses very similar configuration to vis-util and vis-uuid.

The question here is more whether we want to have common code style in this project or whether each package will maintain it's own code style (how it works at the moment).

**Comment by mojoaxel** [comment]
> The question here is more whether we want to have common code style in this project or whether each package will maintain it's own code style

What would it take to separate code-style enforcements into it's own package?
in the end timeline, network and graph3d (hopefully) will be maintained by different teams. Therefor we don't need a common style but maybe it would make sense!?

**Comment by Thomaash** [comment]
ESLint can be configured using a package, but if there will be different code styles in different projects (I don't see much of a point in unifying code styles of separate teams) it would be a bit of an overkill.
Babel can have a preset created in a similar way (I have never done that, not sure how difficult it is).

These tools can be configured using JavaScript, therefore more lightweight version is to export configs from vis-configs and import them in other packages. It would be much simpler to set up and only require vis-configs as dev dependency.

**Comment by mojoaxel** [comment]
One big problem I see with enforcing a code style is that it changes the git history and therefore the "blame" functionality very significantly. Such big changes should be done best together with other big changes (e.g. a typescript rewrite).

@Thomaash Please feel free to create a package `vis-config` or similar! Maybe NOW is the best moment to adopt something like this e.g. in vis-timeline.

**Comment by Thomaash** [comment]
Okay, I'll create a draft vis-config.

By the way, just because there will be central config doesn't mean every project has to use it. We can move TypeScript projects to it but have separate configs for JavaScript projects or different configs for TS and JS files within the same project (ESLint can do this) or even enable it on file by file basis (add eslint-disable comments to the start of all existing files and have it enforced only in the new ones or add eslint-enable to every new file and disable by default to minimize code changes).

**Comment by Thomaash** [comment]
@mojoaxel The vis-configs package is ready for criticism: https://github.com/Thomaash/vis-configs

**Comment by mojoaxel** [comment]
see https://github.com/visjs/vis-dev-utils
