### ISSUE TITLE
Problems with rest parameter on IE11

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-util#59]
I got an error debugging https://github.com/visjs/vis-timeline/issues/72 on IE11.
There seams to be a problem in the `selectiveExtend` function. 

It looks to me that the babel transform of the rest parameter "others" is buggy:
![image](https://user-images.githubusercontent.com/600565/64926828-a3229e80-d802-11e9-90dc-0f6caa248e60.png)

I cannot get this function run in IE without an error :sob:

**Comment by Thomaash** [comment]
Vis Timeline uses Vis Util 1.1.4. Does it happen with 1.1.8?

**Comment by mojoaxel** [comment]
> Vis Timeline uses Vis Util 1.1.4. Does it happen with 1.1.8?

I'm working with the current master branch of vis-util.

**Comment by Thomaash** [comment]
Hmm, I don't see any spreading being done in the function.

**Comment by mojoaxel** [comment]
> Hmm, I don't see any spreading being done in the function.

It's the "rest parameter" `others`:
https://github.com/visjs/vis-util/blob/master/src/util.ts#L249

**Comment by Thomaash** [comment]
But that's not spreading (it just uses the same symbol). Atop of that this gets transformed into a for loop which also doesn't use any spreading.

**Comment by Thomaash** [comment]
In the bundle you have:
```javascript
for (var _len = arguments.length, others = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++) {
  others[_key - 2] = arguments[_key];
}
```

**Comment by mojoaxel** [comment]
You are right...I don't know anymore..I give up!
Maybe It's time that you get yourself a virtual machine with IE11 :wink: 

The timeline is still broken on IE11 (see https://github.com/visjs/vis-timeline/issues/72) and I really want to fix this before releasing vis-timeline@6

**Comment by yotamberk** [comment]
Seems to work for me on IE11 now on latest version.
