### ISSUE TITLE
typescript can not pass

### ISSUE THREAD

**Issue by foxFallingSkies** [visjs/vis-util#725]
when i use typescript .i get the wrong tips in configurator-types.d.ts
declare type NumberInput = readonly [
    initialValue: number,
    min: number,
    max: number,
    step: number
];
can not find name initialValue,min,max,step

**Comment by Thomaash** [comment]
Hi @foxFallingSkies,

I think that your TS is just too old to understand this syntax. Could you try this with up to date TS or at least 4.0?

**Comment by foxFallingSkies** [comment]
> Hi @foxFallingSkies,
> 
> I think that your TS is just too old to understand this syntax. Could you try this with up to date TS or at least 4.0?
thank you for your help
i have fix this problem last night
the reason just because my ts used 3.5.. 
The problem was solved after the upgrade
