### ISSUE TITLE
ERROR in vis-util/declarations/shared/configurator-types.d.ts:33:17 - error TS1005: ',' expected.

### ISSUE THREAD

**Issue by robs23** [visjs/vis-util#748]
I'm getting this strange error when I've added vis-util to my project. My setup is Angular 10 + latest typescript (3.9.5). I'd like to use vis-timeline in particular, but if I'm getting it right, I need to install vis-data and vis-util too. I've installed: 

- vis-timeline (7.4.6) 
- vis-data (7.1.2) 
- vis-util (5.0.1)
- @types/vis

I also installed peer dependencies (hammerjs and keycharm), but it didn't help. How can I get it working?

**Comment by zewazi** [comment]
Having same issue with vis-util 5.0.1:

![image](https://user-images.githubusercontent.com/50274125/106724249-ad6c5500-6610-11eb-9adf-689bf8d68176.png)

Seems like it got broken with commit:
https://github.com/visjs/vis-util/commit/49ade9a91b4e9d6f931e76dc679a233680e714a9

**Comment by Thomaash** [comment]
> latest typescript (3.9.5)

This haven't been latest for months. It works with the latest TS just fine.
