### ISSUE TITLE
distribution fails

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-util#9]
I just installed vis-util@1.1.0. All I got are the following files:
* node_modules/vis-util/LICENSE-APACHE-2.0
* node_modules/vis-util/LICENSE-MIT
* node_modules/vis-util/package.json
* node_modules/vis-util/README.md

This is obviously not not enough for a working release ;-)

**Comment by mojoaxel** [comment]
@Thomaash Could you have a look please!

**Comment by Thomaash** [comment]
I can't find any reason why it's not there, when I run npm pack the files are present they're just not published on npm.

**Comment by Thomaash** [comment]
Maybe just try to republish it no npm.

**Comment by Thomaash** [comment]
Closing since v1.1.1 works.
